name: Build and Deploy to The New Documentation Site
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master","main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build documentation site
        uses: bcc-code/bcc-documentation-base@df7affc3a3f1bc6ac63d9c8d7e281c53c660f847
        with:
          title: BCC Developer Portal
          description: Technical documentation and guides for software development in BCC
          collapse-sidebar: true
          auto-register-components: true
          components-dir: .vuepress/components
          branch: master
          base: /home/
          debug-build: (secrets.ACTIONS_RUNNER_DEBUG == 'true' && secrets.ACTIONS_STEP_DEBUG == 'true')
